# Generated by Django 3.2.3 on 2021-06-10 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='zip_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
