# Generated by Django 3.2.3 on 2021-06-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_resume_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='zip_code',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='zip_code_1',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
